### ISSUE TITLE
Converting UPS Labels

### ISSUE THREAD

**Issue by rattrick1** [nelsontkq/zplify#2]
Hi Nelson,
Have you tried converting UPS labels (either .gif or .png) using this code? It produces a ZPL output but it doesn't appear to be valid. Trying to render it on laberly.com returns the following:

"ERROR: you requested the 1st label, but the specified ZPL doesn't generate any labels"

**Comment by rattrick1** [comment]
Reviewing further, it seems to fail with horizontal images which is how UPS returns them by default

**Comment by nelsontkq** [comment]
I've set the most recent version to rotate if the image's longest size doesn't match the set longest size (usually length). Added a unit test for UPS label and everything looks good. Let me know if you encounter any more issues.
